using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class Carousel : MonoBehaviour {
    public GameObject scrollbar;
    float scroll_pos = 0;
    float[] pos;
    Scrollbar scroll;
    // Start is called before the first frame update
    void Start() {
        scroll = scrollbar.GetComponent<Scrollbar>();
    }

    // Update is called once per frame
    void Update() {
        pos = new float[transform.childCount];
        float distacne = 1f / (pos.Length - 1);
        for (int i = 0; i < pos.Length; i++) {
            pos[i] = distacne * i;
        }

        if (Input.GetMouseButton(0)) {
            scroll_pos = scroll.value;
        }
        else {
            for (int i = 0; i < pos.Length; i++) {
                if (scroll_pos < pos[i] + (distacne / 2) && scroll_pos > pos[i] - (distacne / 2)) {
                    scroll.value = Mathf.Lerp(scroll.value, pos[i], 0.1f);
                }
            }
        }

        for (int i = 0; i < pos.Length; i++) {
            if (scroll_pos < pos[i] + (distacne / 2) && scroll_pos > pos[i] - (distacne / 2)) {
                transform.GetChild(i).localScale = Vector2.Lerp(transform.GetChild(i).localScale, new Vector2(1f, 1f), 0.1f);
                for (int j = 0; j < pos.Length; j++) {
                    if (j != i) {
                        transform.GetChild(j).localScale = Vector2.Lerp(transform.GetChild(j).localScale, new Vector2(0.8f, 0.8f), 0.1f);
                    }
                }
            }
        }
    }
}